# Generated by Django 3.2.9 on 2021-11-23 13:29

import User.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0003_user_nickname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='nickname',
            field=models.CharField(error_messages={'unique': '이미 사용 중인 닉네임입니다'}, max_length=10, null=True, unique=True, validators=[User.validators.validate_no_special_characters]),
        ),
    ]
