# Generated by Django 3.2.9 on 2021-11-23 19:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('post_id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField(default=datetime.date.today, verbose_name='작성 날짜')),
                ('food_name', models.CharField(max_length=50, verbose_name='음식 이름')),
                ('image', models.ImageField(upload_to='', verbose_name='음식 사진')),
                ('content', models.TextField(verbose_name='내용')),
                ('write_time', models.DateTimeField(auto_now=True, verbose_name='작성 시간')),
            ],
            options={
                'verbose_name': '포스트',
                'verbose_name_plural': '포스트',
                'db_table': 'Post',
            },
        ),
        migrations.CreateModel(
            name='Vegan_type',
            fields=[
                ('vegan_id', models.AutoField(primary_key=True, serialize=False)),
                ('vegan_type', models.CharField(max_length=20, verbose_name='비건 타입')),
                ('vegan_sort', models.CharField(choices=[('V', 'Vegetarian'), ('SV', 'Semi_Vegetarian')], max_length=2)),
            ],
            options={
                'verbose_name': '비건 타입',
                'verbose_name_plural': '비건 타입',
                'db_table': 'Vegan_type',
            },
        ),
    ]
