# Generated by Django 3.2.9 on 2021-11-23 13:44

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vegan_type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vegan_type', models.CharField(max_length=20, verbose_name='비건 타입')),
            ],
            options={
                'verbose_name': '비건 타입',
                'verbose_name_plural': '비건 타입',
                'db_table': 'Type',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today, verbose_name='작성 날짜')),
                ('food_name', models.CharField(max_length=50, verbose_name='음식 이름')),
                ('image', models.ImageField(upload_to='', verbose_name='음식 사진')),
                ('content', models.TextField(verbose_name='내용')),
                ('write_time', models.DateTimeField(auto_now=True, verbose_name='작성 시간')),
                ('like', models.ManyToManyField(blank=True, related_name='likes', to=settings.AUTH_USER_MODEL)),
                ('post_vegan_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Post.vegan_type', verbose_name='비건 종류')),
                ('writer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='작성자')),
            ],
            options={
                'verbose_name': '포스트',
                'verbose_name_plural': '포스트',
                'db_table': 'Post',
            },
        ),
    ]
